### ISSUE TITLE
Move datadir_mgr fixture to its own repo

### ISSUE THREAD

**Issue by joelb123** [ncgr/bionorm#6]
The functions in the pytest datadir_mgr fixture are definitely useful in implementing proper test for other NCGR projects, including ones that I code for.  The code isn't very long (~200 lines), but it deserves its own test suite.  Move this to its own repository.

**Comment by adf-ncgr** [comment]
let's prioritize moving bionorm to the legumeinfo organization; looks like you did not accept your last invitation to that organization, which probably explains earlier difficulties you mentioned. So I will be resending an invitation.

**Comment by joelb123** [comment]
Done.
